### ISSUE TITLE
Some JSON alerts attributes should be optional

### ISSUE THREAD

**Issue by jnogol** [idealista/prom2teams#21]
In the current version, the following values are parsed and returned in order to create the Teams message:
``` python
'alert_name': json_alerts_labels_attr['alertname'],
'alert_instance': json_alerts_labels_attr['instance'],
'alert_severity': json_alerts_labels_attr['severity'],
'alert_summary': json_alerts_annotations_attr['summary'],
'alert_description': json_alerts_annotations_attr['description'],
'alert_status': json_alerts_attr['status']
```

Problem is that, depending on the query and/or the alarm rule, `instance`, `summary` or `description` could not be sent by Prometheus. In case this happens, prom2teams fails to parser the input and won't forward the alarm to Microsoft Teams.

**Comment by lindhor** [comment]
I also ran into this one, any guess when this fix might be merged and a new version including it tagged?

**Comment by jnogol** [comment]
Hi Roger,

First of all, thanks for using Prom2Teams. We are working on it and will release the new version soon. 

Regards,
Jose

**Comment by jnogol** [comment]
Hi @lindhor, 

We released a new version (1.1.3) that fixes this. 

Regards,
Jose

**Comment by lindhor** [comment]
Thank you so much for your quick fix! I can confirm that it works and no longer gives an exception for mandatory fields. The list of mandatory attributes is however too strict, since it includes `instance` which is not always sent (for example if you have a rule like `IF absent(container_cpu_load_average_10s{name='mycriticalcontainer})`, i.e. alert if no instances of the container exists on any host). 

Maybe the best approach would be to forward the information you receive and have default values for them instead? Something like:

alertname='unknown'
status='firing'
instance='unknown'
summary='no alert summary specified'

https://github.com/idealista/prom2teams/blob/master/prom2teams/message/parser.py#L8

**Comment by jnogol** [comment]
Hi again Roger,

Thank you for the interesting idea, feel free to open an issue and, if this something critical for you, make us a pull request and we will more than happy to include this feature in the next Prom2Teams release.

Regards,
Jose
