### ISSUE TITLE
[SUPPORT] Configuration For Multiple Connectors

### ISSUE THREAD

**Issue by GingerGraham** [idealista/prom2teams#302]
### Description

I'm looking for some guidance/documentation on some aspects of using the same prom2teams instance to send different types of alert to different destinations.

### Additional Information

I have 2 primary questions that I cannot seem to find answers for in documentation or in general web searching.

1. The readme documentation suggests that it is possible to define additional connectors but it is unclear how to leverage these.  Is there any guidance on how I can get utilise additional connectors?

  - I have a `Connector` and a `Connector2` defined in my config.ini file.  Sending an alert only sends to the default connector
  - I notice the documentation refers to `AnotherConnector` is this a name requirement in the same way as `Connector` appears to be?

2. Along with sending alerts to different channels, is there any way to use different message cards for different alerts sent?

**Comment by abdennour** [comment]
that's really weird! actually i got that part because i worked heavily on msteams integration.
But still the naming convention of connectors keys is not clear.
I mean connectors values are the webhook URLS. .. but what about connector names/keys?
I am asking that question because I can see in the helm chart that the rendering of muliple connectors is done by this snippet:

https://github.com/idealista/prom2teams/blob/2787d324db5529fd020980f857f36635789cdbcc/helm/templates/configmap.yaml#L27-L29

### update
got it by myself! actually it's an ini file format and all those keys under the MS Teams section,,, so it's isolated than other configurations.. Thus no convention on connector key naming.. but just make sure it's RFC 1035 compliant
